/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Product } from './types';

export const COLORS = [
  { name: 'Cosmic Slate', hex: '#334155' },
  { name: 'Electric Blue', hex: '#3B82F6' },
  { name: 'Neon Cyber', hex: '#06B6D4' },
  { name: 'Phantom Black', hex: '#0F172A' },
  { name: 'Arctic White', hex: '#F8FAFC' },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'ProSound X7 Wireless Earbuds',
    brand: 'Sony',
    category: 'Audio',
    price: 129,
    originalPrice: 179,
    image: 'https://picsum.photos/seed/sony_x7/600/600',
    images: [
      'https://picsum.photos/seed/sony_x7/600/600',
      'https://picsum.photos/seed/sony_x7_2/600/600',
      'https://picsum.photos/seed/sony_x7_3/600/600',
      'https://picsum.photos/seed/sony_x7_4/600/600',
      'https://picsum.photos/seed/sony_x7_5/600/600',
    ],
    rating: 4.8,
    reviewCount: 1240,
    inStock: true,
    sku: 'GK-AU-7081',
    shortFeatures: [
      'Industry-leading active noise cancellation (ANC)',
      'Up to 36 hours of battery life with charging case',
      'High-Resolution Audio Wireless certified',
      'Multipoint Bluetooth connection for active switching',
      'IPX4 sweat and water resistance rating',
    ],
    description: [
      'The ProSound X7 offers premium sound engineering designed for the daily commuter and audio purists alike. Equipped with Sony’s custom ANC audio processor, these earbuds block out ambient room noise seamlessly, creating a private studio space wherever you go.',
      'Our intelligent adaptive sound control senses your environment and adjusts ambient settings automatically, providing a balanced sonic stage tailored specifically to your active workflow.',
    ],
    specifications: [
      { key: 'Driver Unit', value: '8.4 mm high-compliance dome' },
      { key: 'Frequency Response', value: '20Hz - 40,000Hz (Hi-Res Audio)' },
      { key: 'Bluetooth Version', value: 'Bluetooth® 5.3 Low Energy' },
      { key: 'Battery Life', value: '8 hrs (ANC On) / 12 hrs (ANC Off) / Up to 36 hrs total' },
      { key: 'Water Resistance', value: 'IPX4 (earbuds only)' },
    ],
    inTheBox: [
      'ProSound X7 Earbuds (Left & Right)',
      'USB-C Quick Charging Case',
      'Silicone Ear Tips (SS, S, M, L sizes)',
      'USB Type-A to USB Type-C Cable',
      'Reference Guide and Warranty Card',
    ],
    isHotDeal: true,
    isNewArrival: false,
  },
  {
    id: '2',
    name: 'UltraWatch Pro 5 Smartwatch',
    brand: 'Apple',
    category: 'Wearables',
    price: 399,
    image: 'https://picsum.photos/seed/apple_watch/600/600',
    images: [
      'https://picsum.photos/seed/apple_watch/600/600',
      'https://picsum.photos/seed/apple_watch_2/600/600',
      'https://picsum.photos/seed/apple_watch_3/600/600',
      'https://picsum.photos/seed/apple_watch_4/600/600',
      'https://picsum.photos/seed/apple_watch_5/600/600',
    ],
    rating: 4.9,
    reviewCount: 2150,
    inStock: true,
    sku: 'GK-WR-9011',
    shortFeatures: [
      'Stunning Always-On Retina display with up to 2000 nits brightness',
      'Advanced ECG and custom blood oxygen level measurements',
      'Precision Dual-Frequency GPS for outdoor navigation',
      'Rugged corrosion-resistant aerospace titanium chassis',
      'Crash Detection and Fall Detection sensors with auto-SOS',
    ],
    description: [
      'The UltraWatch Pro 5 is engineered for athletes, outdoor explorers, and health-conscious professionals. It merges aerospace-grade durability with sophisticated sensors to record biometrics in extreme conditions.',
      'With a screen that is twice as bright as predecessor models and custom quick-action buttons, keeping track of split times, altitudes, and vital data has never been easier.',
    ],
    specifications: [
      { key: 'Chassis Size', value: '45mm / 49mm' },
      { key: 'Display Type', value: 'LTPO OLED Always-On Retina Display' },
      { key: 'Processors', value: 'Apple S9 dual-core 64-bit' },
      { key: 'Sensors', value: 'ECG, SpO2, Temperature, Gyroscope, Barometer' },
      { key: 'Battery Life', value: 'Up to 36 hours (Regular Use) / 72 hours (Low Power Mode)' },
    ],
    inTheBox: [
      'UltraWatch Pro 5 Titanium Body',
      'High-Performance Silicone Ocean Band',
      'Magnetic Fast Charger to USB-C Cable (1m)',
      'Setup Booklet and Safety Documentation',
    ],
    isHotDeal: false,
    isNewArrival: true,
  },
  {
    id: '3',
    name: 'StreamHub 4K Smart TV Stick',
    brand: 'Xiaomi',
    category: 'Smart Home',
    price: 49,
    originalPrice: 69,
    image: 'https://picsum.photos/seed/xiaomi_tv/600/600',
    images: [
      'https://picsum.photos/seed/xiaomi_tv/600/600',
      'https://picsum.photos/seed/xiaomi_tv_2/600/600',
      'https://picsum.photos/seed/xiaomi_tv_3/600/600',
      'https://picsum.photos/seed/xiaomi_tv_4/600/600',
      'https://picsum.photos/seed/xiaomi_tv_5/600/600',
    ],
    rating: 4.4,
    reviewCount: 890,
    inStock: true,
    sku: 'GK-SH-1102',
    shortFeatures: [
      'Full cinematic 4K streaming with Dolby Vision + HDR10+',
      'Built-in Google Assistant for native voice search compatibility',
      'Chromecast built-in: cast mobile screens instantly',
      'Dolby Atmos and DTS-HD cinematic surround sound audio support',
      'Includes premium Bluetooth 360° voice-control remote',
    ],
    description: [
      'Bring your old display to life with the Xiaomi StreamHub 4K Smart TV Stick. Powered by Google TV, it collates your favorite subscription catalogs onto a single curated homepage customizable by user profiles.',
      'Its incredibly small footprint plugs straight into any HDMI port, and runs on an octa-core CPU to deliver lag-free stream rendering across games, movies, and apps.',
    ],
    specifications: [
      { key: 'Resolution Output', value: '4K Ultra HD (3840 x 2160) @ 60 FPS' },
      { key: 'Operating System', value: 'Google TV / Android TV 11' },
      { key: 'Processor', value: 'Quad-core Cortex-A35' },
      { key: 'Memory & Storage', value: '2GB RAM + 8GB eMMC Flash' },
      { key: 'Wireless Protocols', value: 'Wi-Fi 2.4GHz/5GHz, Bluetooth 5.0' },
    ],
    inTheBox: [
      'Xiaomi StreamHub TV Stick',
      'Bluetooth Voice Remote with Shortcut Buttons',
      'USB-A to Micro-USB Power Cable',
      'Power Adapter Brick',
      'HDMI Extension Cable extender',
    ],
    isHotDeal: true,
    isNewArrival: false,
  },
  {
    id: '4',
    name: 'NovaBuds Max ANC Headphones',
    brand: 'Bose',
    category: 'Audio',
    price: 249,
    image: 'https://picsum.photos/seed/bose_nova/600/600',
    images: [
      'https://picsum.photos/seed/bose_nova/600/600',
      'https://picsum.photos/seed/bose_nova_2/600/600',
      'https://picsum.photos/seed/bose_nova_3/600/600',
      'https://picsum.photos/seed/bose_nova_4/600/600',
      'https://picsum.photos/seed/bose_nova_5/600/600',
    ],
    rating: 4.7,
    reviewCount: 512,
    inStock: true,
    sku: 'GK-AU-4512',
    shortFeatures: [
      'Custom Active Noise Cancellation with Aware Mode setting',
      'Proprietary TriPort acoustic design for full-range high-fidelity audio',
      'Lightweight synthetic leather ear cups for long-duration wearability',
      'Up to 24 hours of listening time on one single full charge',
      'Custom app equalizer to customize treble, mid-ranges and bass',
    ],
    description: [
      'Uncompromising audio meets exquisite luxury. The NovaBuds Max wireless headphones block the external atmosphere and plunge you into your playlist with crisp vocals and rich, pulsating low-ranges.',
      'Built with ultra-soft pressure-relieving cushions and high-tensile headband adjustments, they settle naturally during lengthy professional development or entertainment sessions.',
    ],
    specifications: [
      { key: 'Acoustic Architecture', value: 'Closed-back over-ear design' },
      { key: 'Battery Charging Speed', value: '15 min charge translates to 3 hours of playback' },
      { key: 'Microphone Array', value: '4 environmental sensors + voice pickup beamformer' },
      { key: 'Connection Codecs', value: 'SBC, AAC, aptX Adaptive' },
      { key: 'Weight', value: '240 grams' },
    ],
    inTheBox: [
      'NovaBuds Max Headphones',
      'Protective Zipper Hardcase',
      '3.5mm-to-2.5mm Audio Cable (1.2m)',
      'USB-C Charging Cable',
      'Quick Start Instruction Manual',
    ],
    isHotDeal: false,
    isNewArrival: false,
  },
  {
    id: '5',
    name: 'SnapPhone 15 Ultra',
    brand: 'Samsung',
    category: 'Smartphones',
    price: 999,
    originalPrice: 1149,
    image: 'https://picsum.photos/seed/samsung_15/600/600',
    images: [
      'https://picsum.photos/seed/samsung_15/600/600',
      'https://picsum.photos/seed/samsung_15_2/600/600',
      'https://picsum.photos/seed/samsung_15_3/600/600',
      'https://picsum.photos/seed/samsung_15_4/600/600',
      'https://picsum.photos/seed/samsung_15_5/600/600',
    ],
    rating: 4.9,
    reviewCount: 1680,
    inStock: true,
    sku: 'GK-SP-9502',
    shortFeatures: [
      'Dynamic AMOLED 2X 120Hz display with absolute true blacks',
      'Revolutionary 200MP Space Zoom Quad-Camera setup',
      'Snapdragon 8 Gen 3 chip optimized for real-time mobile ray-tracing',
      'Embedded stylus S-Pen with latency reduced under 2.8ms',
      'Vast 5000mAh battery supporting 45W ultra-fast wireless charging',
    ],
    description: [
      'SnapPhone 15 Ultra represents the absolute peak of mobile performance. Capturing incredible detail using the professional 200MP sensor, this smartphone leverages AI computation to render vibrant evening and portrait captures.',
      'Underneath, the Snapdragon chipset works alongside vapor-chamber thermal controls to sustain high framerates during intense mobile gaming sessions or continuous productivity multi-tasking.',
    ],
    specifications: [
      { key: 'Screen Size', value: '6.8" Screen (Dynamic AMOLED 1440 x 3088 px)' },
      { key: 'Chipset Processor', value: 'Qualcomm Snapdragon 8 Gen 3 (4nm)' },
      { key: 'Primary Camera System', value: '200MP wide + 50MP + 12MP + 10MP with 100x zoom' },
      { key: 'Battery Capacity', value: '5,000 mAh Li-Ion (45W wired charging)' },
      { key: 'OS Framework', value: 'OneUI 6.1 (Android 14)' },
    ],
    inTheBox: [
      'SnapPhone 15 Ultra Device',
      'Embedded S-Pen Stylus Unit',
      'USB-C to USB-C Dual Shielded Cable',
      'SIM Insertion Tool pin',
      'Safety, Regulatory, and Warranty Pamphlets',
    ],
    isHotDeal: true,
    isNewArrival: false,
  },
  {
    id: '6',
    name: 'PowerCore 30000 Portable Charger',
    brand: 'Anker',
    category: 'Accessories', // Fits Accessories category
    price: 59,
    image: 'https://picsum.photos/seed/anker_power/600/600',
    images: [
      'https://picsum.photos/seed/anker_power/600/600',
      'https://picsum.photos/seed/anker_power_2/600/600',
      'https://picsum.photos/seed/anker_power_3/600/600',
      'https://picsum.photos/seed/anker_power_4/600/600',
      'https://picsum.photos/seed/anker_power_5/600/600',
    ],
    rating: 4.6,
    reviewCount: 940,
    inStock: true,
    sku: 'GK-AC-1002',
    shortFeatures: [
      'Massive 30,000mAh cell capacity delivers 10+ full typical smartphone charges',
      'PowerIQ 3.0 delivers 30W maximum charging speed to compatible laptops',
      'Dual USB-A and USB-C output ports charge up to 3 units simultaneously',
      'Reinforced external housing handles bumps, scrapes, and light spills',
      'Trickle Charger safety core for low-demand accessories usage',
    ],
    description: [
      'Never worry about losing energy again. The Anker PowerCore provides a huge electrical reserve for smartphones, tablets, handheld game units, and lightweight laptops looking for power during long flights or emergency outdoor excursions.',
      'Equipped with Anker’s MultiProtect active biosensor array, temperature fluctuations and current overflows are instantly mitigated before they ever put your connected devises at risk.',
    ],
    specifications: [
      { key: 'Battery Cell Capacity', value: '30,000 mAh / 111 Wh' },
      { key: 'Max Charge Output', value: '30W Power Delivery via USB-C' },
      { key: 'Output Terminals', value: '1x USB-C PD, 2x USB-A PowerIQ' },
      { key: 'Recharge Time Boost', value: 'Approx. 4.5 hours with a 30W PD wall charger' },
      { key: 'Dimensions & Weight', value: '180 x 85 x 30 mm; 550g' },
    ],
    inTheBox: [
      'PowerCore 30000 Battery Bank Block',
      'USB-C to USB-C Heavy Duty Charging Cable',
      'Velvety Travel Drawstring Mesh Sleeve',
      'User Registration Manual',
    ],
    isHotDeal: false,
    isNewArrival: false,
  },
  {
    id: '7',
    name: 'GamePad Elite Controller',
    brand: 'Generic',
    category: 'Gaming',
    price: 79,
    image: 'https://picsum.photos/seed/gamepad_elite/600/600',
    images: [
      'https://picsum.photos/seed/gamepad_elite/600/600',
      'https://picsum.photos/seed/gamepad_elite_2/600/600',
      'https://picsum.photos/seed/gamepad_elite_3/600/600',
      'https://picsum.photos/seed/gamepad_elite_4/600/600',
      'https://picsum.photos/seed/gamepad_elite_5/600/600',
    ],
    rating: 4.5,
    reviewCount: 320,
    inStock: true,
    sku: 'GK-GA-2001',
    shortFeatures: [
      'Includes 4 rear programmable paddle buttons for quick-remap functions',
      'Hall-effect non-drift analog joysticks prevent tracking errors',
      'Quick mechanical triggers reduce click depths by up to 80%',
      'Rubberized high-grip texturing contours ergonomic hand positions',
      'Supports cross-platform Bluetooth, Xbox, PC, iOS, and Android',
    ],
    description: [
      'Engineered specifically with high-tier competitive gaming in mind. The GamePad Elite handles multiple layout configurations on the fly, with satisfying click switches signaling inputs immediately.',
      'The durable construction boasts a built-in gyroscopic tracking sensor and 12 adjustable rumble modules designed to make every vibration, blast, and tire drift tactile.',
    ],
    specifications: [
      { key: 'Analog Sensors', value: 'Electromagnetic Hall Effect Joysticks' },
      { key: 'Connectivity Options', value: 'Wireless Bluetooth® 5.1 / 2.4Ghz Dongle / USB-C' },
      { key: 'Battery Capacity', value: '1,200mAh Lithium Ion (Up to 15 hours play time)' },
      { key: 'Haptic Feedback', value: 'Asymmetric Dual Rumble Core Motors' },
      { key: 'Shell Materials', value: 'ABS with textured non-slip grips' },
    ],
    inTheBox: [
      'GamePad Elite controller',
      'Replaceable Analog Joystick Caps (Spherical & Flat heads)',
      '2.4Ghz USB-A Connection Receiver Dongle',
      'Heavy-Braid USB-C to USB-A Cable (2m)',
      'Layout Assembly Booklet',
    ],
    isHotDeal: false,
    isNewArrival: true,
  },
  {
    id: '8',
    name: 'AirPods Max 2nd Gen',
    brand: 'Apple',
    category: 'Audio',
    price: 549,
    image: 'https://picsum.photos/seed/apple_max/600/600',
    images: [
      'https://picsum.photos/seed/apple_max/600/600',
      'https://picsum.photos/seed/apple_max_2/600/600',
      'https://picsum.photos/seed/apple_max_3/600/600',
      'https://picsum.photos/seed/apple_max_4/600/600',
      'https://picsum.photos/seed/apple_max_5/600/600',
    ],
    rating: 4.8,
    reviewCount: 1450,
    inStock: true,
    sku: 'GK-AU-8002',
    shortFeatures: [
      'Apple H2 audio processors drive custom sound computational adjustments',
      'Incredible Personalized Spatial Audio with active head-tracking tech',
      'Custom mesh canopy distributes headband weight for fatigue-free rest',
      'Equipped with upgraded USB-C audio port + fast charging support',
      'Unbelievable high-contrast active ambient noise cancelation system',
    ],
    description: [
      'AirPods Max represents a stunning fusion of acoustic brilliance, premium metals, and adaptive systems. Every element is aligned to conform perfectly under high acoustic environments.',
      'From the memory-foam cushions clad in custom breathable mesh material, to the highly precise digital crown, adjust settings instantly as you traverse multi-room layouts.',
    ],
    specifications: [
      { key: 'Integrated Chip', value: 'Apple H2 chip inside each ear cup' },
      { key: 'Acoustic Driver', value: 'Apple-engineered 40mm dynamic driver' },
      { key: 'Bluetooth Spec', value: 'Bluetooth® 5.3 Audio Architecture' },
      { key: 'Battery Life Spec', value: 'Up to 20 hours with active ANC & Spatial Audio enabled' },
      { key: 'Wired audio connection', value: 'Analog audio playback via USB-C' },
    ],
    inTheBox: [
      'AirPods Max 2nd Gen Over-Ear Unit',
      'Ultra-thin Protective Smart Case sleeve',
      'USB-C High-Speed Charging Cable',
      'Core documentation',
    ],
    isHotDeal: false,
    isNewArrival: false,
  },
  {
    id: '9',
    name: 'SmartHome Hub v3',
    brand: 'Xiaomi',
    category: 'Smart Home',
    price: 89,
    originalPrice: 109,
    image: 'https://picsum.photos/seed/xiaomi_hub/600/600',
    images: [
      'https://picsum.photos/seed/xiaomi_hub/600/600',
      'https://picsum.photos/seed/xiaomi_hub_2/600/600',
      'https://picsum.photos/seed/xiaomi_hub_3/600/600',
      'https://picsum.photos/seed/xiaomi_hub_4/600/600',
      'https://picsum.photos/seed/xiaomi_hub_5/600/600',
    ],
    rating: 4.5,
    reviewCount: 420,
    inStock: true,
    sku: 'GK-SM-3199',
    shortFeatures: [
      'Multi-protocol integration coordinates Zigbee, Bluetooth, and Matter systems',
      'Local automation engine executes routines even offline',
      'Supports Apple Home, Google Home, and Alexa integrations',
      'High-range internal 2T2R Wi-Fi antenna boosts wall penetration',
      'Sleek circular design blends into standard decorative spaces',
    ],
    description: [
      'The SmartHome Hub v3 acts as the master conductor for modern automated environments. It connects security sensors, cameras, smart lightbulbs, and appliances into a single, cohesive web of commands.',
      'With the newly adopted Matter framework natively integrated, products across distinct brands can now interface locally with latency under 10ms.',
    ],
    specifications: [
      { key: 'Integrated Protocols', value: 'Zigbee 3.0, Bluetooth Mesh, Matter, BLE' },
      { key: 'Internal Range', value: 'Up to 150 meters in open-space line of sight' },
      { key: 'USB interface', value: 'USB-C (Power supply only)' },
      { key: 'Processors Core', value: 'Dual-core 1.0 GHz processor along with 128MB RAM' },
      { key: 'Housing specs', value: 'V-0 premium flame-retardant industrial polymer' },
    ],
    inTheBox: [
      'SmartHome Hub v3 Controller Block',
      'Wall Mount Assembly Screws & Plates',
      'Micro-to-USB-C flat power cord',
      'Product adapter',
      'System Setup Checklist Manual',
    ],
    isHotDeal: true,
    isNewArrival: false,
  },
  {
    id: '10',
    name: 'UltraBook Pro 14" Laptop',
    brand: 'Samsung',
    category: 'Laptops',
    price: 1299,
    image: 'https://picsum.photos/seed/samsung_laptop/600/600',
    images: [
      'https://picsum.photos/seed/samsung_laptop/600/600',
      'https://picsum.photos/seed/samsung_laptop_2/600/600',
      'https://picsum.photos/seed/samsung_laptop_3/600/600',
      'https://picsum.photos/seed/samsung_laptop_4/600/600',
      'https://picsum.photos/seed/samsung_laptop_5/600/600',
    ],
    rating: 4.8,
    reviewCount: 310,
    inStock: true,
    sku: 'GK-LT-7712',
    shortFeatures: [
      'Breath-taking 14" Dynamic AMOLED Dynamic 3K display panel',
      'Intel Core Ultra 7 processor with dedicated NPU neural engines',
      'Intel Arc Graphics handles creative high-fidelity design work',
      'Incredibly thin 11.6mm profiles, weight capped under 1.25kg',
      'Quad AKG speaker arrays with Dolby Atmos spatial tuning',
    ],
    description: [
      'Experience absolute power on the move. Built with premium milled aerospace aluminum and high-precision key triggers, UltraBook Pro 14 coordinates high-demand computations seamlessly while maintaining thermal equilibrium.',
      'The outstanding 3K OLED viewport operates on variable frequency (60Hz to 120Hz) to save power during standard text editing, and instantly speeds up for fluid fluid visuals during action streams or multimedia projects.',
    ],
    specifications: [
      { key: 'Processor Unit', value: 'Intel® Core™ Ultra 7 155H Processor (Up to 4.80 GHz)' },
      { key: 'RAM Hardware', value: '16GB LPDDR5X (On-board Dual Channel)' },
      { key: 'Disk Drive Space', value: '512GB NVMe PCIe Gen4 Solid State Drive' },
      { key: 'Display Hardware', value: '14" 3K AMOLED (2880 x 1800), 120Hz, 120% DCI-P3' },
      { key: 'Ports Interface', value: '2x Thunderbolt™ 4, 1x USB-A 3.2, 1x HDMI 2.1, MicroSD Reader' },
    ],
    inTheBox: [
      'UltraBook Pro 14 Laptop Computer',
      'Super-compact 65W GaN USB-C Charger',
      'High-Speed USB-C to USB-C Interconnect Cable (1.8m)',
      'User Quick Start Setup Guide',
    ],
    isHotDeal: false,
    isNewArrival: true,
  },
  {
    id: '11',
    name: 'RiftVR Headset Lite',
    brand: 'Generic',
    category: 'Gaming',
    price: 299,
    originalPrice: 349,
    image: 'https://picsum.photos/seed/generic_vr/600/600',
    images: [
      'https://picsum.photos/seed/generic_vr/600/600',
      'https://picsum.photos/seed/generic_vr_2/600/600',
      'https://picsum.photos/seed/generic_vr_3/600/600',
      'https://picsum.photos/seed/generic_vr_4/600/600',
      'https://picsum.photos/seed/generic_vr_5/600/600',
    ],
    rating: 4.3,
    reviewCount: 280,
    inStock: true,
    sku: 'GK-GA-1188',
    shortFeatures: [
      'Completely standalone operation - no computer tethering or wires required',
      'Dual 2K Fast-Switch LCD lenses resolve crystal-clear details',
      'Integrated spatial 3D audio built inside the strap mechanics',
      'Includes 2 advanced hand controllers with active tracking sensors',
      'Supports seamless Casting to compatible mobile screens and television boxes',
    ],
    description: [
      'Pioneer the metaverse with the RiftVR Headset Lite. Combining an exceptionally fast tracking chip and advanced lenses, this virtual reality gear plunges users into expansive 3D worlds, workouts, and multi-user environments.',
      'The custom head gear is counter-weighted perfectly across front and rear contact lines, easing pressure around the sinus-bridge for long immersive sessions.',
    ],
    specifications: [
      { key: 'Display Grid Output', value: '1832 x 1920 pixels per eye resolution' },
      { key: 'System Clock speed', value: 'Qualcomm Snapdragon XR2 Gen 1' },
      { key: 'Refresh Rates Spec', value: 'Supports 72Hz, 90Hz, and 120Hz configurations' },
      { key: 'Battery specs', value: 'Built-in 3,600mAh battery (approx. 2 to 2.5 hours active use)' },
      { key: 'Tracking Cameras', value: '4 internal spatial infrared sensor lenses' },
    ],
    inTheBox: [
      'RiftVR Lite Standalone Headset Unit',
      '2x Dynamic Motion Trackers with wrist straps',
      'Glasses Spacer Cushion Adapter',
      'USB-C Charging cord alongside adapter brick',
      'Safety and user setup handbook',
    ],
    isHotDeal: true,
    isNewArrival: false,
  },
  {
    id: '12',
    name: 'WristFit Band 4',
    brand: 'Xiaomi',
    category: 'Wearables',
    price: 39,
    image: 'https://picsum.photos/seed/xiaomi_fit/600/600',
    images: [
      'https://picsum.photos/seed/xiaomi_fit/600/600',
      'https://picsum.photos/seed/xiaomi_fit_2/600/600',
      'https://picsum.photos/seed/xiaomi_fit_3/600/600',
      'https://picsum.photos/seed/xiaomi_fit_4/600/600',
      'https://picsum.photos/seed/xiaomi_fit_5/600/600',
    ],
    rating: 4.6,
    reviewCount: 1620,
    inStock: true,
    sku: 'GK-WR-4002',
    shortFeatures: [
      'Gorgeous 1.62" high-contrast AMOLED bezel-less viewport screen',
      'Over 150 diverse athletic training modes tracked in real time',
      'Continuous 24h heart rate & blood oxygen monitoring sensors',
      'Incredible battery lifecycle lasts up to 16 consecutive days',
      '5ATM deep-water resistance protects against heavy immersion sweeps',
    ],
    description: [
      'Get massive analytics from an extremely slender watchband. The WristFit Band 4 tracks heart patterns, stress, sleep architecture, and precise athletic split numbers for an incredibly economic investment.',
      'The custom watch interface is interchangeable, and connects with the smartphone system to push text, call alert, and quick camera controls right onto your wrist.',
    ],
    specifications: [
      { key: 'Screen Display Panel', value: '1.62" AMOLED Touch, 326 PPI, 600 nits' },
      { key: 'Water-proof rating', value: '5 ATM (Water resistance up to 50 meters)' },
      { key: 'Sensors Inside', value: 'PPG Heart Rate Sensor, 3-axis Accelerometer, Gyrometer' },
      { key: 'Battery spec', value: '190mAh capacity, up to 16 days typical duration' },
      { key: 'Body Weight', value: 'Just 13.5 grams (without strap attached)' },
    ],
    inTheBox: [
      'Xiaomi WristFit Band 4 Core Tracker',
      'Hypoallergenic Black TPU Wristband strap',
      'Magnetic Custom Fast Charging Cable',
      'Official User Manual documentation',
    ],
    isHotDeal: false,
    isNewArrival: true,
  },
];

export const MOCK_REVIEWS = [
  {
    id: 'r1',
    name: 'David K.',
    date: '2026-05-12',
    rating: 5,
    comment: 'Absolute masterpiece! The sound output on these earbuds is incredible, and the Active Noise Cancellation works perfectly in subways. Exceeded all my expectations. GadgetsKini had this shipped in less than 24 hours!',
  },
  {
    id: 'r2',
    name: 'Sarah M.',
    date: '2026-04-29',
    rating: 4,
    comment: 'Incredible product. Sleek construction and fits extremely well in smaller ears. My only wish is that the battery case supported wireless Qi induction natively. Highly recommended for workspace focus!',
  },
  {
    id: 'r3',
    name: 'Tariq A.',
    date: '2026-05-20',
    rating: 5,
    comment: 'The best value ever. I was skeptical of the lower price compared to local stores, but this is 100% authentic. The micro-animations on screen look slick and the customer care support was highly polite.',
  },
];

export const TEAM_MEMBERS = [
  {
    id: 't1',
    name: 'Vikram Singh',
    role: 'Chief Executive Officer',
    avatar: 'https://picsum.photos/seed/ceo/200/200',
    bio: 'Tech futurist and designer with 15+ years leading ecommerce operations and hardware curation.',
  },
  {
    id: 't2',
    name: 'Dr. Evelyn Carter',
    role: 'Head of Tech Curation',
    avatar: 'https://picsum.photos/seed/curator/200/200',
    bio: 'Former acoustics developer specialized in finding and benchmarking bleeding-edge hardware.',
  },
  {
    id: 't3',
    name: 'Marcus Vance',
    role: 'Customer Experience Lead',
    avatar: 'https://picsum.photos/seed/cx/200/200',
    bio: 'Devoted advocate for customer needs. Overlooks our worldwide warranty processing and fast chat response.',
  },
];

export const FAQS = [
  {
    group: 'Orders & Payments',
    questions: [
      {
        q: 'What payment options does GadgetsKini accept?',
        a: 'We support all major global credit cards (Visa, Mastercard, American Express), PayPal, Apple Pay, and Google Pay. All transactions are fully encrypted through secure payment gateways.',
      },
      {
        q: 'Can I apply a coupon AFTER placing my order?',
        a: 'Coupons must be applied in the Cart page before proceeding to the Checkout. Unfortunately, our automated system cannot adjust invoice totals once the checkout transaction has compiled successfully.',
      },
      {
        q: 'Is there a discount code available for new customers?',
        a: 'Yes! Use the code "TECH10" during checkout to save 10% on your entire order. Subscribe to our newsletter to receive weekly exclusive drop codes.',
      },
    ],
  },
  {
    group: 'Shipping & Delivery',
    questions: [
      {
        q: 'How much does shipping cost, and is there free shipping?',
        a: 'We offer FREE Standard Shipping on all nationwide orders above $75. For orders below $75, standard ground shipping is a flat fee of $9.99. Express and Next Day options are available at checkout.',
      },
      {
        q: 'Where do my gadget products ship from?',
        a: 'All items are kept physically inside our fully automated warehouse hubs in Boston, MA and Austin, TX, allowing fast dispatch times across mainland regions.',
      },
      {
        q: 'How can I track the delivery progress of my gadgets?',
        a: 'Once your order has been dispatched, a shipping transition code will be populated inside your Account Dashboard, and a tracking URL will be automatically sent to the email registered on file.',
      },
    ],
  },
  {
    group: 'Returns & Refunds',
    questions: [
      {
        q: 'What is the standard GadgetsKini return window?',
        a: 'We provide a 30-day hassle-free return window. If you are not satisfied with your device, you can return it in its original internal package casing and box configuration for a complete refund.',
      },
      {
        q: 'Are return shipping labels covered by you?',
        a: 'Yes! If the product demonstrates faults or transit damage, return postage is free. For voluntary changes of mind, a standard carrier label deduction of $5.99 will apply to the refunded sum.',
      },
    ],
  },
  {
    group: 'Products & Warranty',
    questions: [
      {
        q: 'Are all product listings authentic and original?',
        a: 'Yes, 100%! We are certified partner outlets with brands like Apple, Samsung, Sony, Bose, and Xiaomi. Every single item contains serial credentials validation labels inside.',
      },
      {
        q: 'Does my purchase include warranty cover?',
        a: 'A GadgetsKini purchase includes a complimentary 2-Year Comprehensive Mechanical Warranty. This covers all internal sensor errors, current issues, or audio drivers breakdowns completely.',
      },
    ],
  },
  {
    group: 'Account & Rewards',
    questions: [
      {
        q: 'What are GadgetsKini Rewards Points?',
        a: 'It is our loyalty system! For every dollar spent on our store, you earn 1 Rewards Point. Points can be redeemed during checkout sessions for direct savings off product list prices.',
      },
      {
        q: 'How do I change my registered billing address?',
        a: 'Simply access the My Account screen, jump to the Address Registry tab, and click the Edit option on your saved cards to update entries.',
      },
    ],
  },
];
