/**
 * Auto-generated by scripts/fetch-products.ts — 2026-05-27T14:05:55.121Z
 * Source: dummyjson.com (no API key required)
 * 38 products
 *
 * To use: replace MOCK_PRODUCTS in src/data.ts with this array
 */

import { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    "id": "78",
    "name": "Apple MacBook Pro 14 Inch Space Grey",
    "brand": "Apple",
    "category": "Laptops",
    "price": 1999.99,
    "originalPrice": 2098.41,
    "image": "https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/1.webp",
      "https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/2.webp",
      "https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/3.webp",
      "https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/thumbnail.webp"
    ],
    "rating": 3.7,
    "reviewCount": 189,
    "inStock": true,
    "sku": "GK-LA-0078",
    "shortFeatures": [],
    "description": [
      "The MacBook Pro 14 Inch in Space Grey is a powerful and sleek laptop, featuring Apple's M1 Pro chip for exceptional performance and a stunning Retina display."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Apple"
      },
      {
        "key": "Weight",
        "value": "9g"
      },
      {
        "key": "Dimensions",
        "value": "20.03 × 9.54 × 14.82 mm"
      },
      {
        "key": "Warranty",
        "value": "3 year warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 2 weeks"
      }
    ],
    "inTheBox": [
      "Laptop",
      "USB-C Power Adapter",
      "Quick Start Guide"
    ],
    "isHotDeal": false,
    "isNewArrival": true
  },
  {
    "id": "79",
    "name": "Asus Zenbook Pro Dual Screen Laptop",
    "brand": "Asus",
    "category": "Laptops",
    "price": 1799.99,
    "originalPrice": 2025.65,
    "image": "https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/1.webp",
      "https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/2.webp",
      "https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/3.webp",
      "https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/thumbnail.webp"
    ],
    "rating": 4,
    "reviewCount": 111,
    "inStock": true,
    "sku": "GK-LA-0079",
    "shortFeatures": [],
    "description": [
      "The Asus Zenbook Pro Dual Screen Laptop is a high-performance device with dual screens, providing productivity and versatility for creative professionals."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Asus"
      },
      {
        "key": "Weight",
        "value": "9g"
      },
      {
        "key": "Dimensions",
        "value": "16.6 × 11.49 × 10.89 mm"
      },
      {
        "key": "Warranty",
        "value": "3 year warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 1 month"
      }
    ],
    "inTheBox": [
      "Laptop",
      "USB-C Power Adapter",
      "Quick Start Guide"
    ],
    "isHotDeal": true,
    "isNewArrival": true
  },
  {
    "id": "80",
    "name": "Huawei Matebook X Pro",
    "brand": "Huawei",
    "category": "Laptops",
    "price": 1399.99,
    "originalPrice": 1544.9,
    "image": "https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/1.webp",
      "https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/2.webp",
      "https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/3.webp",
      "https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/thumbnail.webp"
    ],
    "rating": 5,
    "reviewCount": 279,
    "inStock": true,
    "sku": "GK-LA-0080",
    "shortFeatures": [],
    "description": [
      "The Huawei Matebook X Pro is a slim and stylish laptop with a high-resolution touchscreen display, offering a premium experience for users on the go."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Huawei"
      },
      {
        "key": "Weight",
        "value": "9g"
      },
      {
        "key": "Dimensions",
        "value": "18.21 × 22.83 × 17.26 mm"
      },
      {
        "key": "Warranty",
        "value": "No warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships overnight"
      }
    ],
    "inTheBox": [
      "Laptop",
      "USB-C Power Adapter",
      "Quick Start Guide"
    ],
    "isHotDeal": false,
    "isNewArrival": false
  },
  {
    "id": "81",
    "name": "Lenovo Yoga 920",
    "brand": "Lenovo",
    "category": "Laptops",
    "price": 1099.99,
    "originalPrice": 1177.09,
    "image": "https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/1.webp",
      "https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/2.webp",
      "https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/3.webp",
      "https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/thumbnail.webp"
    ],
    "rating": 2.9,
    "reviewCount": 177,
    "inStock": true,
    "sku": "GK-LA-0081",
    "shortFeatures": [],
    "description": [
      "The Lenovo Yoga 920 is a 2-in-1 convertible laptop with a flexible hinge, allowing you to use it as a laptop or tablet, offering versatility and portability."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Lenovo"
      },
      {
        "key": "Weight",
        "value": "9g"
      },
      {
        "key": "Dimensions",
        "value": "20.84 × 22.68 × 17.39 mm"
      },
      {
        "key": "Warranty",
        "value": "6 months warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 2 weeks"
      }
    ],
    "inTheBox": [
      "Laptop",
      "USB-C Power Adapter",
      "Quick Start Guide"
    ],
    "isHotDeal": false,
    "isNewArrival": false
  },
  {
    "id": "82",
    "name": "New DELL XPS 13 9300 Laptop",
    "brand": "Dell",
    "category": "Laptops",
    "price": 1499.99,
    "originalPrice": 1702.41,
    "image": "https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/1.webp",
      "https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/2.webp",
      "https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/3.webp",
      "https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/thumbnail.webp"
    ],
    "rating": 2.7,
    "reviewCount": 243,
    "inStock": true,
    "sku": "GK-LA-0082",
    "shortFeatures": [],
    "description": [
      "The New DELL XPS 13 9300 Laptop is a compact and powerful device, featuring a virtually borderless InfinityEdge display and high-end performance for various tasks."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Dell"
      },
      {
        "key": "Weight",
        "value": "2g"
      },
      {
        "key": "Dimensions",
        "value": "13.76 × 29 × 21.42 mm"
      },
      {
        "key": "Warranty",
        "value": "2 year warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 2 weeks"
      }
    ],
    "inTheBox": [
      "Laptop",
      "USB-C Power Adapter",
      "Quick Start Guide"
    ],
    "isHotDeal": true,
    "isNewArrival": false
  },
  {
    "id": "99",
    "name": "Amazon Echo Plus",
    "brand": "Amazon",
    "category": "Accessories",
    "price": 99.99,
    "originalPrice": 113.72,
    "image": "https://cdn.dummyjson.com/product-images/mobile-accessories/amazon-echo-plus/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/mobile-accessories/amazon-echo-plus/1.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/amazon-echo-plus/2.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/amazon-echo-plus/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/amazon-echo-plus/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/amazon-echo-plus/thumbnail.webp"
    ],
    "rating": 5,
    "reviewCount": 204,
    "inStock": true,
    "sku": "GK-MO-0099",
    "shortFeatures": [
      "The Amazon Echo Plus is a smart speaker with built-in Alexa voice control",
      "It features premium sound quality and serves as a hub for controlling smart home devices"
    ],
    "description": [
      "The Amazon Echo Plus is a smart speaker with built-in Alexa voice control. It features premium sound quality and serves as a hub for controlling smart home devices."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Amazon"
      },
      {
        "key": "Weight",
        "value": "5g"
      },
      {
        "key": "Dimensions",
        "value": "12.68 × 15.24 × 27.46 mm"
      },
      {
        "key": "Warranty",
        "value": "6 months warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 1 week"
      }
    ],
    "inTheBox": [
      "Device",
      "Charging Cable",
      "User Manual"
    ],
    "isHotDeal": true,
    "isNewArrival": true
  },
  {
    "id": "100",
    "name": "Apple Airpods",
    "brand": "Apple",
    "category": "Accessories",
    "price": 129.99,
    "originalPrice": 153.91,
    "image": "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/1.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/2.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/3.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/thumbnail.webp"
    ],
    "rating": 4.2,
    "reviewCount": 279,
    "inStock": true,
    "sku": "GK-MO-0100",
    "shortFeatures": [
      "The Apple Airpods offer a seamless wireless audio experience",
      "With easy pairing, high-quality sound, and Siri integration, they are perfect for on-the-go listening"
    ],
    "description": [
      "The Apple Airpods offer a seamless wireless audio experience. With easy pairing, high-quality sound, and Siri integration, they are perfect for on-the-go listening."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Apple"
      },
      {
        "key": "Weight",
        "value": "4g"
      },
      {
        "key": "Dimensions",
        "value": "25.79 × 18.38 × 11.53 mm"
      },
      {
        "key": "Warranty",
        "value": "3 year warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 3-5 business days"
      }
    ],
    "inTheBox": [
      "Device",
      "Charging Cable",
      "User Manual"
    ],
    "isHotDeal": true,
    "isNewArrival": true
  },
  {
    "id": "101",
    "name": "Apple AirPods Max Silver",
    "brand": "Apple",
    "category": "Accessories",
    "price": 549.99,
    "originalPrice": 637.08,
    "image": "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/1.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/thumbnail.webp"
    ],
    "rating": 3.5,
    "reviewCount": 189,
    "inStock": true,
    "sku": "GK-MO-0101",
    "shortFeatures": [
      "Experience immersive sound in style"
    ],
    "description": [
      "The Apple AirPods Max in Silver are premium over-ear headphones with high-fidelity audio, adaptive EQ, and active noise cancellation. Experience immersive sound in style."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Apple"
      },
      {
        "key": "Weight",
        "value": "2g"
      },
      {
        "key": "Dimensions",
        "value": "24.88 × 14.9 × 27.54 mm"
      },
      {
        "key": "Warranty",
        "value": "No warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 2 weeks"
      }
    ],
    "inTheBox": [
      "Device",
      "Charging Cable",
      "User Manual"
    ],
    "isHotDeal": true,
    "isNewArrival": false
  },
  {
    "id": "102",
    "name": "Apple Airpower Wireless Charger",
    "brand": "Apple",
    "category": "Accessories",
    "price": 79.99,
    "originalPrice": 83.74,
    "image": "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpower-wireless-charger/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpower-wireless-charger/1.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpower-wireless-charger/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpower-wireless-charger/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpower-wireless-charger/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpower-wireless-charger/thumbnail.webp"
    ],
    "rating": 3.7,
    "reviewCount": 216,
    "inStock": true,
    "sku": "GK-MO-0102",
    "shortFeatures": [
      "The Apple AirPower Wireless Charger provides a convenient way to charge your compatible Apple devices wirelessly",
      "Simply place your devices on the charging mat for effortless charging"
    ],
    "description": [
      "The Apple AirPower Wireless Charger provides a convenient way to charge your compatible Apple devices wirelessly. Simply place your devices on the charging mat for effortless charging."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Apple"
      },
      {
        "key": "Weight",
        "value": "5g"
      },
      {
        "key": "Dimensions",
        "value": "25.25 × 25.44 × 10.98 mm"
      },
      {
        "key": "Warranty",
        "value": "2 year warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 1 week"
      }
    ],
    "inTheBox": [
      "Device",
      "Charging Cable",
      "User Manual"
    ],
    "isHotDeal": false,
    "isNewArrival": false
  },
  {
    "id": "103",
    "name": "Apple HomePod Mini Cosmic Grey",
    "brand": "Apple",
    "category": "Accessories",
    "price": 99.99,
    "originalPrice": 122.09,
    "image": "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-homepod-mini-cosmic-grey/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-homepod-mini-cosmic-grey/1.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-homepod-mini-cosmic-grey/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-homepod-mini-cosmic-grey/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-homepod-mini-cosmic-grey/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-homepod-mini-cosmic-grey/thumbnail.webp"
    ],
    "rating": 4.6,
    "reviewCount": 72,
    "inStock": true,
    "sku": "GK-MO-0103",
    "shortFeatures": [],
    "description": [
      "The Apple HomePod Mini in Cosmic Grey is a compact smart speaker that delivers impressive audio and integrates seamlessly with the Apple ecosystem for a smart home experience."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Apple"
      },
      {
        "key": "Weight",
        "value": "10g"
      },
      {
        "key": "Dimensions",
        "value": "16.02 × 29.2 × 19.81 mm"
      },
      {
        "key": "Warranty",
        "value": "3 months warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 1 month"
      }
    ],
    "inTheBox": [
      "Device",
      "Charging Cable",
      "User Manual"
    ],
    "isHotDeal": true,
    "isNewArrival": false
  },
  {
    "id": "104",
    "name": "Apple iPhone Charger",
    "brand": "Apple",
    "category": "Accessories",
    "price": 19.99,
    "originalPrice": 24.53,
    "image": "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/1.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/2.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/thumbnail.webp"
    ],
    "rating": 4.2,
    "reviewCount": 168,
    "inStock": true,
    "sku": "GK-MO-0104",
    "shortFeatures": [
      "The Apple iPhone Charger is a high-quality charger designed for fast and efficient charging of your iPhone",
      "Ensure your device stays powered up and ready to go"
    ],
    "description": [
      "The Apple iPhone Charger is a high-quality charger designed for fast and efficient charging of your iPhone. Ensure your device stays powered up and ready to go."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Apple"
      },
      {
        "key": "Weight",
        "value": "1g"
      },
      {
        "key": "Dimensions",
        "value": "13.63 × 26.25 × 5.95 mm"
      },
      {
        "key": "Warranty",
        "value": "1 year warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 2 weeks"
      }
    ],
    "inTheBox": [
      "Device",
      "Charging Cable",
      "User Manual"
    ],
    "isHotDeal": true,
    "isNewArrival": false
  },
  {
    "id": "105",
    "name": "Apple MagSafe Battery Pack",
    "brand": "Apple",
    "category": "Accessories",
    "price": 99.99,
    "originalPrice": 120.72,
    "image": "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/1.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/2.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/thumbnail.webp"
    ],
    "rating": 3.6,
    "reviewCount": 123,
    "inStock": true,
    "sku": "GK-MO-0105",
    "shortFeatures": [
      "Attach it magnetically for a secure connection"
    ],
    "description": [
      "The Apple MagSafe Battery Pack is a portable and convenient way to add extra battery life to your MagSafe-compatible iPhone. Attach it magnetically for a secure connection."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Apple"
      },
      {
        "key": "Weight",
        "value": "6g"
      },
      {
        "key": "Dimensions",
        "value": "15.4 × 11.89 × 19.67 mm"
      },
      {
        "key": "Warranty",
        "value": "2 year warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships overnight"
      }
    ],
    "inTheBox": [
      "Device",
      "Charging Cable",
      "User Manual"
    ],
    "isHotDeal": true,
    "isNewArrival": false
  },
  {
    "id": "106",
    "name": "Apple Watch Series 4 Gold",
    "brand": "Apple",
    "category": "Accessories",
    "price": 349.99,
    "originalPrice": 397.81,
    "image": "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-watch-series-4-gold/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-watch-series-4-gold/1.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-watch-series-4-gold/2.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-watch-series-4-gold/3.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-watch-series-4-gold/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-watch-series-4-gold/thumbnail.webp"
    ],
    "rating": 2.7,
    "reviewCount": 135,
    "inStock": true,
    "sku": "GK-MO-0106",
    "shortFeatures": [],
    "description": [
      "The Apple Watch Series 4 in Gold is a stylish and advanced smartwatch with features like heart rate monitoring, fitness tracking, and a beautiful Retina display."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Apple"
      },
      {
        "key": "Weight",
        "value": "6g"
      },
      {
        "key": "Dimensions",
        "value": "27.69 × 28.03 × 7.11 mm"
      },
      {
        "key": "Warranty",
        "value": "6 months warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 1 month"
      }
    ],
    "inTheBox": [
      "Device",
      "Charging Cable",
      "User Manual"
    ],
    "isHotDeal": true,
    "isNewArrival": false
  },
  {
    "id": "107",
    "name": "Beats Flex Wireless Earphones",
    "brand": "Beats",
    "category": "Accessories",
    "price": 49.99,
    "originalPrice": 53.03,
    "image": "https://cdn.dummyjson.com/product-images/mobile-accessories/beats-flex-wireless-earphones/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/mobile-accessories/beats-flex-wireless-earphones/1.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/beats-flex-wireless-earphones/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/beats-flex-wireless-earphones/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/beats-flex-wireless-earphones/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/beats-flex-wireless-earphones/thumbnail.webp"
    ],
    "rating": 4.2,
    "reviewCount": 150,
    "inStock": true,
    "sku": "GK-MO-0107",
    "shortFeatures": [
      "The Beats Flex Wireless Earphones offer a comfortable and versatile audio experience",
      "With magnetic earbuds and up to 12 hours of battery life, they are ideal for everyday use"
    ],
    "description": [
      "The Beats Flex Wireless Earphones offer a comfortable and versatile audio experience. With magnetic earbuds and up to 12 hours of battery life, they are ideal for everyday use."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Beats"
      },
      {
        "key": "Weight",
        "value": "8g"
      },
      {
        "key": "Dimensions",
        "value": "17.86 × 25.74 × 23.09 mm"
      },
      {
        "key": "Warranty",
        "value": "1 year warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 1-2 business days"
      }
    ],
    "inTheBox": [
      "Device",
      "Charging Cable",
      "User Manual"
    ],
    "isHotDeal": false,
    "isNewArrival": false
  },
  {
    "id": "108",
    "name": "iPhone 12 Silicone Case with MagSafe Plum",
    "brand": "Apple",
    "category": "Accessories",
    "price": 29.99,
    "originalPrice": 34.81,
    "image": "https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/1.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/2.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/3.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/4.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp"
    ],
    "rating": 3.6,
    "reviewCount": 66,
    "inStock": true,
    "sku": "GK-MO-0108",
    "shortFeatures": [
      "The iPhone 12 Silicone Case with MagSafe in Plum is a stylish and protective case designed for the iPhone 12",
      "It features MagSafe technology for easy attachment of accessories"
    ],
    "description": [
      "The iPhone 12 Silicone Case with MagSafe in Plum is a stylish and protective case designed for the iPhone 12. It features MagSafe technology for easy attachment of accessories."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Apple"
      },
      {
        "key": "Weight",
        "value": "7g"
      },
      {
        "key": "Dimensions",
        "value": "12.49 × 11.29 × 23.52 mm"
      },
      {
        "key": "Warranty",
        "value": "3 months warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 3-5 business days"
      }
    ],
    "inTheBox": [
      "Device",
      "Charging Cable",
      "User Manual"
    ],
    "isHotDeal": true,
    "isNewArrival": false
  },
  {
    "id": "109",
    "name": "Monopod",
    "brand": "TechGear",
    "category": "Accessories",
    "price": 19.99,
    "originalPrice": 21.87,
    "image": "https://cdn.dummyjson.com/product-images/mobile-accessories/monopod/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/mobile-accessories/monopod/1.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/monopod/2.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/monopod/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/monopod/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/monopod/thumbnail.webp"
    ],
    "rating": 4.4,
    "reviewCount": 87,
    "inStock": true,
    "sku": "GK-MO-0109",
    "shortFeatures": [
      "The Monopod is a versatile camera accessory for stable and adjustable shooting",
      "Perfect for capturing selfies, group photos, and videos with ease"
    ],
    "description": [
      "The Monopod is a versatile camera accessory for stable and adjustable shooting. Perfect for capturing selfies, group photos, and videos with ease."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "TechGear"
      },
      {
        "key": "Weight",
        "value": "10g"
      },
      {
        "key": "Dimensions",
        "value": "8.8 × 12.93 × 21.1 mm"
      },
      {
        "key": "Warranty",
        "value": "1 year warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 1-2 business days"
      }
    ],
    "inTheBox": [
      "Device",
      "Charging Cable",
      "User Manual"
    ],
    "isHotDeal": false,
    "isNewArrival": false
  },
  {
    "id": "110",
    "name": "Selfie Lamp with iPhone",
    "brand": "GadgetMaster",
    "category": "Accessories",
    "price": 14.99,
    "originalPrice": 18.6,
    "image": "https://cdn.dummyjson.com/product-images/mobile-accessories/selfie-lamp-with-iphone/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/mobile-accessories/selfie-lamp-with-iphone/1.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/selfie-lamp-with-iphone/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/selfie-lamp-with-iphone/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/selfie-lamp-with-iphone/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/selfie-lamp-with-iphone/thumbnail.webp"
    ],
    "rating": 3.6,
    "reviewCount": 276,
    "inStock": true,
    "sku": "GK-MO-0110",
    "shortFeatures": [
      "The Selfie Lamp with iPhone is a portable and adjustable LED light designed to enhance your selfies and video calls",
      "Attach it to your iPhone for well-lit photos"
    ],
    "description": [
      "The Selfie Lamp with iPhone is a portable and adjustable LED light designed to enhance your selfies and video calls. Attach it to your iPhone for well-lit photos."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "GadgetMaster"
      },
      {
        "key": "Weight",
        "value": "10g"
      },
      {
        "key": "Dimensions",
        "value": "5.26 × 13.84 × 22.83 mm"
      },
      {
        "key": "Warranty",
        "value": "Lifetime warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 2 weeks"
      }
    ],
    "inTheBox": [
      "Device",
      "Charging Cable",
      "User Manual"
    ],
    "isHotDeal": true,
    "isNewArrival": false
  },
  {
    "id": "111",
    "name": "Selfie Stick Monopod",
    "brand": "SnapTech",
    "category": "Accessories",
    "price": 12.99,
    "originalPrice": 16.06,
    "image": "https://cdn.dummyjson.com/product-images/mobile-accessories/selfie-stick-monopod/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/mobile-accessories/selfie-stick-monopod/1.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/selfie-stick-monopod/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/selfie-stick-monopod/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/selfie-stick-monopod/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/selfie-stick-monopod/thumbnail.webp"
    ],
    "rating": 3.9,
    "reviewCount": 63,
    "inStock": true,
    "sku": "GK-MO-0111",
    "shortFeatures": [
      "The Selfie Stick Monopod is a extendable and foldable device for capturing the perfect selfie or group photo",
      "Compatible with smartphones and cameras"
    ],
    "description": [
      "The Selfie Stick Monopod is a extendable and foldable device for capturing the perfect selfie or group photo. Compatible with smartphones and cameras."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "SnapTech"
      },
      {
        "key": "Weight",
        "value": "2g"
      },
      {
        "key": "Dimensions",
        "value": "24.76 × 26.38 × 21.39 mm"
      },
      {
        "key": "Warranty",
        "value": "3 year warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 1-2 business days"
      }
    ],
    "inTheBox": [
      "Device",
      "Charging Cable",
      "User Manual"
    ],
    "isHotDeal": true,
    "isNewArrival": false
  },
  {
    "id": "112",
    "name": "TV Studio Camera Pedestal",
    "brand": "ProVision",
    "category": "Accessories",
    "price": 499.99,
    "originalPrice": 545.3,
    "image": "https://cdn.dummyjson.com/product-images/mobile-accessories/tv-studio-camera-pedestal/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/mobile-accessories/tv-studio-camera-pedestal/1.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/tv-studio-camera-pedestal/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/tv-studio-camera-pedestal/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/tv-studio-camera-pedestal/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/mobile-accessories/tv-studio-camera-pedestal/thumbnail.webp"
    ],
    "rating": 2.8,
    "reviewCount": 198,
    "inStock": true,
    "sku": "GK-MO-0112",
    "shortFeatures": [
      "Ideal for broadcast and production"
    ],
    "description": [
      "The TV Studio Camera Pedestal is a professional-grade camera support system for smooth and precise camera movements in a studio setting. Ideal for broadcast and production."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "ProVision"
      },
      {
        "key": "Weight",
        "value": "4g"
      },
      {
        "key": "Dimensions",
        "value": "29.84 × 11.01 × 6.81 mm"
      },
      {
        "key": "Warranty",
        "value": "3 months warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 1-2 business days"
      }
    ],
    "inTheBox": [
      "Device",
      "Charging Cable",
      "User Manual"
    ],
    "isHotDeal": false,
    "isNewArrival": false
  },
  {
    "id": "121",
    "name": "iPhone 5s",
    "brand": "Apple",
    "category": "Smartphones",
    "price": 199.99,
    "originalPrice": 229.64,
    "image": "https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/1.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/2.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/3.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/thumbnail.webp"
    ],
    "rating": 2.8,
    "reviewCount": 84,
    "inStock": true,
    "sku": "GK-SM-0121",
    "shortFeatures": [
      "The iPhone 5s is a classic smartphone known for its compact design and advanced features during its release",
      "While it's an older model, it still provides a reliable user experience"
    ],
    "description": [
      "The iPhone 5s is a classic smartphone known for its compact design and advanced features during its release. While it's an older model, it still provides a reliable user experience."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Apple"
      },
      {
        "key": "Weight",
        "value": "2g"
      },
      {
        "key": "Dimensions",
        "value": "5.29 × 18.38 × 17.72 mm"
      },
      {
        "key": "Warranty",
        "value": "Lifetime warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 1 month"
      }
    ],
    "inTheBox": [
      "Device",
      "USB-C Cable",
      "SIM Ejector Tool",
      "Quick Start Guide"
    ],
    "isHotDeal": true,
    "isNewArrival": true
  },
  {
    "id": "122",
    "name": "iPhone 6",
    "brand": "Apple",
    "category": "Smartphones",
    "price": 299.99,
    "originalPrice": 321.5,
    "image": "https://cdn.dummyjson.com/product-images/smartphones/iphone-6/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/smartphones/iphone-6/1.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/iphone-6/2.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/iphone-6/3.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/iphone-6/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/iphone-6/thumbnail.webp"
    ],
    "rating": 3.4,
    "reviewCount": 294,
    "inStock": true,
    "sku": "GK-SM-0122",
    "shortFeatures": [
      "The iPhone 6 is a stylish and capable smartphone with a larger display and improved performance",
      "It introduced new features and design elements, making it a popular choice in its time"
    ],
    "description": [
      "The iPhone 6 is a stylish and capable smartphone with a larger display and improved performance. It introduced new features and design elements, making it a popular choice in its time."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Apple"
      },
      {
        "key": "Weight",
        "value": "7g"
      },
      {
        "key": "Dimensions",
        "value": "11 × 9.1 × 9.67 mm"
      },
      {
        "key": "Warranty",
        "value": "1 month warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships overnight"
      }
    ],
    "inTheBox": [
      "Device",
      "USB-C Cable",
      "SIM Ejector Tool",
      "Quick Start Guide"
    ],
    "isHotDeal": false,
    "isNewArrival": true
  },
  {
    "id": "123",
    "name": "iPhone 13 Pro",
    "brand": "Apple",
    "category": "Smartphones",
    "price": 1099.99,
    "originalPrice": 1213.72,
    "image": "https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/1.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/2.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/3.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp"
    ],
    "rating": 4.1,
    "reviewCount": 237,
    "inStock": true,
    "sku": "GK-SM-0123",
    "shortFeatures": [
      "It offers advanced features for users who demand top-notch technology"
    ],
    "description": [
      "The iPhone 13 Pro is a cutting-edge smartphone with a powerful camera system, high-performance chip, and stunning display. It offers advanced features for users who demand top-notch technology."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Apple"
      },
      {
        "key": "Weight",
        "value": "8g"
      },
      {
        "key": "Dimensions",
        "value": "12.63 × 5.28 × 14.29 mm"
      },
      {
        "key": "Warranty",
        "value": "3 year warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 2 weeks"
      }
    ],
    "inTheBox": [
      "Device",
      "USB-C Cable",
      "SIM Ejector Tool",
      "Quick Start Guide"
    ],
    "isHotDeal": false,
    "isNewArrival": false
  },
  {
    "id": "124",
    "name": "iPhone X",
    "brand": "Apple",
    "category": "Smartphones",
    "price": 899.99,
    "originalPrice": 1119.25,
    "image": "https://cdn.dummyjson.com/product-images/smartphones/iphone-x/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/smartphones/iphone-x/1.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/iphone-x/2.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/iphone-x/3.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/iphone-x/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/iphone-x/thumbnail.webp"
    ],
    "rating": 2.5,
    "reviewCount": 264,
    "inStock": true,
    "sku": "GK-SM-0124",
    "shortFeatures": [
      "It represents a milestone in iPhone design and innovation"
    ],
    "description": [
      "The iPhone X is a flagship smartphone featuring a bezel-less OLED display, facial recognition technology (Face ID), and impressive performance. It represents a milestone in iPhone design and innovation."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Apple"
      },
      {
        "key": "Weight",
        "value": "1g"
      },
      {
        "key": "Dimensions",
        "value": "21.88 × 24.19 × 14.19 mm"
      },
      {
        "key": "Warranty",
        "value": "3 months warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 3-5 business days"
      }
    ],
    "inTheBox": [
      "Device",
      "USB-C Cable",
      "SIM Ejector Tool",
      "Quick Start Guide"
    ],
    "isHotDeal": true,
    "isNewArrival": false
  },
  {
    "id": "125",
    "name": "Oppo A57",
    "brand": "Oppo",
    "category": "Smartphones",
    "price": 249.99,
    "originalPrice": 256.22,
    "image": "https://cdn.dummyjson.com/product-images/smartphones/oppo-a57/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/smartphones/oppo-a57/1.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/oppo-a57/2.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/oppo-a57/3.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/oppo-a57/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/oppo-a57/thumbnail.webp"
    ],
    "rating": 3.9,
    "reviewCount": 288,
    "inStock": true,
    "sku": "GK-SM-0125",
    "shortFeatures": [
      "The Oppo A57 is a mid-range smartphone known for its sleek design and capable features",
      "It offers a balance of performance and affordability, making it a popular choice"
    ],
    "description": [
      "The Oppo A57 is a mid-range smartphone known for its sleek design and capable features. It offers a balance of performance and affordability, making it a popular choice."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Oppo"
      },
      {
        "key": "Weight",
        "value": "5g"
      },
      {
        "key": "Dimensions",
        "value": "7.2 × 10.74 × 23.68 mm"
      },
      {
        "key": "Warranty",
        "value": "Lifetime warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 3-5 business days"
      }
    ],
    "inTheBox": [
      "Device",
      "USB-C Cable",
      "SIM Ejector Tool",
      "Quick Start Guide"
    ],
    "isHotDeal": false,
    "isNewArrival": false
  },
  {
    "id": "126",
    "name": "Oppo F19 Pro Plus",
    "brand": "Oppo",
    "category": "Smartphones",
    "price": 399.99,
    "originalPrice": 491.63,
    "image": "https://cdn.dummyjson.com/product-images/smartphones/oppo-f19-pro-plus/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/smartphones/oppo-f19-pro-plus/1.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/oppo-f19-pro-plus/2.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/oppo-f19-pro-plus/3.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/oppo-f19-pro-plus/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/oppo-f19-pro-plus/thumbnail.webp"
    ],
    "rating": 3.5,
    "reviewCount": 213,
    "inStock": true,
    "sku": "GK-SM-0126",
    "shortFeatures": [
      "The Oppo F19 Pro Plus is a feature-rich smartphone with a focus on camera capabilities",
      "It boasts advanced photography features and a powerful performance for a premium user experience"
    ],
    "description": [
      "The Oppo F19 Pro Plus is a feature-rich smartphone with a focus on camera capabilities. It boasts advanced photography features and a powerful performance for a premium user experience."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Oppo"
      },
      {
        "key": "Weight",
        "value": "6g"
      },
      {
        "key": "Dimensions",
        "value": "6.78 × 25.17 × 8.4 mm"
      },
      {
        "key": "Warranty",
        "value": "3 year warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 1 week"
      }
    ],
    "inTheBox": [
      "Device",
      "USB-C Cable",
      "SIM Ejector Tool",
      "Quick Start Guide"
    ],
    "isHotDeal": true,
    "isNewArrival": false
  },
  {
    "id": "127",
    "name": "Oppo K1",
    "brand": "Oppo",
    "category": "Smartphones",
    "price": 299.99,
    "originalPrice": 367.14,
    "image": "https://cdn.dummyjson.com/product-images/smartphones/oppo-k1/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/smartphones/oppo-k1/1.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/oppo-k1/2.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/oppo-k1/3.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/oppo-k1/4.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/oppo-k1/thumbnail.webp"
    ],
    "rating": 4.3,
    "reviewCount": 90,
    "inStock": true,
    "sku": "GK-SM-0127",
    "shortFeatures": [
      "The Oppo K1 series offers a range of smartphones with various features and specifications",
      "Known for their stylish design and reliable performance, the Oppo K1 series caters to diverse user preferences"
    ],
    "description": [
      "The Oppo K1 series offers a range of smartphones with various features and specifications. Known for their stylish design and reliable performance, the Oppo K1 series caters to diverse user preferences."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Oppo"
      },
      {
        "key": "Weight",
        "value": "5g"
      },
      {
        "key": "Dimensions",
        "value": "13.89 × 10.63 × 16.6 mm"
      },
      {
        "key": "Warranty",
        "value": "1 month warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 1-2 business days"
      }
    ],
    "inTheBox": [
      "Device",
      "USB-C Cable",
      "SIM Ejector Tool",
      "Quick Start Guide"
    ],
    "isHotDeal": true,
    "isNewArrival": false
  },
  {
    "id": "128",
    "name": "Realme C35",
    "brand": "Realme",
    "category": "Smartphones",
    "price": 149.99,
    "originalPrice": 177.08,
    "image": "https://cdn.dummyjson.com/product-images/smartphones/realme-c35/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/smartphones/realme-c35/1.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/realme-c35/2.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/realme-c35/3.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/realme-c35/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/realme-c35/thumbnail.webp"
    ],
    "rating": 4.2,
    "reviewCount": 69,
    "inStock": true,
    "sku": "GK-SM-0128",
    "shortFeatures": [
      "The Realme C35 is a budget-friendly smartphone with a focus on providing essential features for everyday use",
      "It offers a reliable performance and user-friendly experience"
    ],
    "description": [
      "The Realme C35 is a budget-friendly smartphone with a focus on providing essential features for everyday use. It offers a reliable performance and user-friendly experience."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Realme"
      },
      {
        "key": "Weight",
        "value": "2g"
      },
      {
        "key": "Dimensions",
        "value": "25.28 × 8.14 × 29.53 mm"
      },
      {
        "key": "Warranty",
        "value": "3 year warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships overnight"
      }
    ],
    "inTheBox": [
      "Device",
      "USB-C Cable",
      "SIM Ejector Tool",
      "Quick Start Guide"
    ],
    "isHotDeal": true,
    "isNewArrival": false
  },
  {
    "id": "129",
    "name": "Realme X",
    "brand": "Realme",
    "category": "Smartphones",
    "price": 299.99,
    "originalPrice": 322.4,
    "image": "https://cdn.dummyjson.com/product-images/smartphones/realme-x/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/smartphones/realme-x/1.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/realme-x/2.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/realme-x/3.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/realme-x/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/realme-x/thumbnail.webp"
    ],
    "rating": 3.7,
    "reviewCount": 234,
    "inStock": true,
    "sku": "GK-SM-0129",
    "shortFeatures": [
      "The Realme X is a mid-range smartphone known for its sleek design and impressive display",
      "It offers a good balance of performance and camera capabilities for users seeking a quality device"
    ],
    "description": [
      "The Realme X is a mid-range smartphone known for its sleek design and impressive display. It offers a good balance of performance and camera capabilities for users seeking a quality device."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Realme"
      },
      {
        "key": "Weight",
        "value": "4g"
      },
      {
        "key": "Dimensions",
        "value": "25.59 × 21.42 × 12.75 mm"
      },
      {
        "key": "Warranty",
        "value": "1 month warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 3-5 business days"
      }
    ],
    "inTheBox": [
      "Device",
      "USB-C Cable",
      "SIM Ejector Tool",
      "Quick Start Guide"
    ],
    "isHotDeal": false,
    "isNewArrival": false
  },
  {
    "id": "130",
    "name": "Realme XT",
    "brand": "Realme",
    "category": "Smartphones",
    "price": 349.99,
    "originalPrice": 395.51,
    "image": "https://cdn.dummyjson.com/product-images/smartphones/realme-xt/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/smartphones/realme-xt/1.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/realme-xt/2.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/realme-xt/3.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/realme-xt/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/realme-xt/thumbnail.webp"
    ],
    "rating": 4.6,
    "reviewCount": 141,
    "inStock": true,
    "sku": "GK-SM-0130",
    "shortFeatures": [
      "The Realme XT is a feature-rich smartphone with a focus on camera technology",
      "It comes equipped with advanced camera sensors, delivering high-quality photos and videos for photography enthusiasts"
    ],
    "description": [
      "The Realme XT is a feature-rich smartphone with a focus on camera technology. It comes equipped with advanced camera sensors, delivering high-quality photos and videos for photography enthusiasts."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Realme"
      },
      {
        "key": "Weight",
        "value": "3g"
      },
      {
        "key": "Dimensions",
        "value": "24.98 × 26.73 × 6.5 mm"
      },
      {
        "key": "Warranty",
        "value": "3 year warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 1 month"
      }
    ],
    "inTheBox": [
      "Device",
      "USB-C Cable",
      "SIM Ejector Tool",
      "Quick Start Guide"
    ],
    "isHotDeal": true,
    "isNewArrival": false
  },
  {
    "id": "131",
    "name": "Samsung Galaxy S7",
    "brand": "Samsung",
    "category": "Smartphones",
    "price": 299.99,
    "originalPrice": 372.89,
    "image": "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s7/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s7/1.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s7/2.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s7/3.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s7/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s7/thumbnail.webp"
    ],
    "rating": 3.3,
    "reviewCount": 261,
    "inStock": true,
    "sku": "GK-SM-0131",
    "shortFeatures": [
      "The Samsung Galaxy S7 is a flagship smartphone known for its sleek design and advanced features",
      "It features a high-resolution display, powerful camera, and robust performance"
    ],
    "description": [
      "The Samsung Galaxy S7 is a flagship smartphone known for its sleek design and advanced features. It features a high-resolution display, powerful camera, and robust performance."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Samsung"
      },
      {
        "key": "Weight",
        "value": "10g"
      },
      {
        "key": "Dimensions",
        "value": "13.55 × 24.24 × 5.63 mm"
      },
      {
        "key": "Warranty",
        "value": "3 months warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 3-5 business days"
      }
    ],
    "inTheBox": [
      "Device",
      "USB-C Cable",
      "SIM Ejector Tool",
      "Quick Start Guide"
    ],
    "isHotDeal": true,
    "isNewArrival": false
  },
  {
    "id": "132",
    "name": "Samsung Galaxy S8",
    "brand": "Samsung",
    "category": "Smartphones",
    "price": 499.99,
    "originalPrice": 620.72,
    "image": "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s8/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s8/1.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s8/2.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s8/3.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s8/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s8/thumbnail.webp"
    ],
    "rating": 4.4,
    "reviewCount": 165,
    "inStock": false,
    "sku": "GK-SM-0132",
    "shortFeatures": [
      "The Samsung Galaxy S8 is a premium smartphone with an Infinity Display, offering a stunning visual experience",
      "It boasts advanced camera capabilities and cutting-edge technology"
    ],
    "description": [
      "The Samsung Galaxy S8 is a premium smartphone with an Infinity Display, offering a stunning visual experience. It boasts advanced camera capabilities and cutting-edge technology."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Samsung"
      },
      {
        "key": "Weight",
        "value": "6g"
      },
      {
        "key": "Dimensions",
        "value": "23.05 × 26.88 × 15.73 mm"
      },
      {
        "key": "Warranty",
        "value": "2 year warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 1 week"
      }
    ],
    "inTheBox": [
      "Device",
      "USB-C Cable",
      "SIM Ejector Tool",
      "Quick Start Guide"
    ],
    "isHotDeal": true,
    "isNewArrival": false
  },
  {
    "id": "133",
    "name": "Samsung Galaxy S10",
    "brand": "Samsung",
    "category": "Smartphones",
    "price": 699.99,
    "originalPrice": 741.44,
    "image": "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s10/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s10/1.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s10/2.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s10/3.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s10/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s10/thumbnail.webp"
    ],
    "rating": 3.1,
    "reviewCount": 216,
    "inStock": true,
    "sku": "GK-SM-0133",
    "shortFeatures": [
      "It represents innovation and excellence in smartphone technology"
    ],
    "description": [
      "The Samsung Galaxy S10 is a flagship device featuring a dynamic AMOLED display, versatile camera system, and powerful performance. It represents innovation and excellence in smartphone technology."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Samsung"
      },
      {
        "key": "Weight",
        "value": "9g"
      },
      {
        "key": "Dimensions",
        "value": "27.41 × 15.26 × 27.02 mm"
      },
      {
        "key": "Warranty",
        "value": "No warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 2 weeks"
      }
    ],
    "inTheBox": [
      "Device",
      "USB-C Cable",
      "SIM Ejector Tool",
      "Quick Start Guide"
    ],
    "isHotDeal": false,
    "isNewArrival": false
  },
  {
    "id": "134",
    "name": "Vivo S1",
    "brand": "Vivo",
    "category": "Smartphones",
    "price": 249.99,
    "originalPrice": 278.29,
    "image": "https://cdn.dummyjson.com/product-images/smartphones/vivo-s1/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/smartphones/vivo-s1/1.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/vivo-s1/2.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/vivo-s1/3.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/vivo-s1/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/vivo-s1/thumbnail.webp"
    ],
    "rating": 3.5,
    "reviewCount": 213,
    "inStock": true,
    "sku": "GK-SM-0134",
    "shortFeatures": [
      "The Vivo S1 is a stylish and mid-range smartphone offering a blend of design and performance",
      "It features a vibrant display, capable camera system, and reliable functionality"
    ],
    "description": [
      "The Vivo S1 is a stylish and mid-range smartphone offering a blend of design and performance. It features a vibrant display, capable camera system, and reliable functionality."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Vivo"
      },
      {
        "key": "Weight",
        "value": "4g"
      },
      {
        "key": "Dimensions",
        "value": "14.06 × 11.79 × 6.78 mm"
      },
      {
        "key": "Warranty",
        "value": "6 months warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 3-5 business days"
      }
    ],
    "inTheBox": [
      "Device",
      "USB-C Cable",
      "SIM Ejector Tool",
      "Quick Start Guide"
    ],
    "isHotDeal": true,
    "isNewArrival": false
  },
  {
    "id": "135",
    "name": "Vivo V9",
    "brand": "Vivo",
    "category": "Smartphones",
    "price": 299.99,
    "originalPrice": 364.38,
    "image": "https://cdn.dummyjson.com/product-images/smartphones/vivo-v9/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/smartphones/vivo-v9/1.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/vivo-v9/2.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/vivo-v9/3.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/vivo-v9/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/vivo-v9/thumbnail.webp"
    ],
    "rating": 3.6,
    "reviewCount": 231,
    "inStock": true,
    "sku": "GK-SM-0135",
    "shortFeatures": [
      "The Vivo V9 is a smartphone known for its sleek design and emphasis on capturing high-quality selfies",
      "It features a notch display, dual-camera setup, and a modern design"
    ],
    "description": [
      "The Vivo V9 is a smartphone known for its sleek design and emphasis on capturing high-quality selfies. It features a notch display, dual-camera setup, and a modern design."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Vivo"
      },
      {
        "key": "Weight",
        "value": "4g"
      },
      {
        "key": "Dimensions",
        "value": "19.85 × 21.83 × 13.04 mm"
      },
      {
        "key": "Warranty",
        "value": "2 year warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 1 month"
      }
    ],
    "inTheBox": [
      "Device",
      "USB-C Cable",
      "SIM Ejector Tool",
      "Quick Start Guide"
    ],
    "isHotDeal": true,
    "isNewArrival": false
  },
  {
    "id": "136",
    "name": "Vivo X21",
    "brand": "Vivo",
    "category": "Smartphones",
    "price": 499.99,
    "originalPrice": 605.39,
    "image": "https://cdn.dummyjson.com/product-images/smartphones/vivo-x21/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/smartphones/vivo-x21/1.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/vivo-x21/2.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/vivo-x21/3.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/vivo-x21/thumbnail.webp",
      "https://cdn.dummyjson.com/product-images/smartphones/vivo-x21/thumbnail.webp"
    ],
    "rating": 4.3,
    "reviewCount": 291,
    "inStock": true,
    "sku": "GK-SM-0136",
    "shortFeatures": [
      "The Vivo X21 is a premium smartphone with a focus on cutting-edge technology",
      "It features an in-display fingerprint sensor, a high-resolution display, and advanced camera capabilities"
    ],
    "description": [
      "The Vivo X21 is a premium smartphone with a focus on cutting-edge technology. It features an in-display fingerprint sensor, a high-resolution display, and advanced camera capabilities."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Vivo"
      },
      {
        "key": "Weight",
        "value": "10g"
      },
      {
        "key": "Dimensions",
        "value": "22.49 × 21.62 × 27.88 mm"
      },
      {
        "key": "Warranty",
        "value": "1 year warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 1-2 business days"
      }
    ],
    "inTheBox": [
      "Device",
      "USB-C Cable",
      "SIM Ejector Tool",
      "Quick Start Guide"
    ],
    "isHotDeal": true,
    "isNewArrival": false
  },
  {
    "id": "159",
    "name": "iPad Mini 2021 Starlight",
    "brand": "Apple",
    "category": "Laptops",
    "price": 499.99,
    "originalPrice": 518.88,
    "image": "https://cdn.dummyjson.com/product-images/tablets/ipad-mini-2021-starlight/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/tablets/ipad-mini-2021-starlight/1.webp",
      "https://cdn.dummyjson.com/product-images/tablets/ipad-mini-2021-starlight/2.webp",
      "https://cdn.dummyjson.com/product-images/tablets/ipad-mini-2021-starlight/3.webp",
      "https://cdn.dummyjson.com/product-images/tablets/ipad-mini-2021-starlight/4.webp",
      "https://cdn.dummyjson.com/product-images/tablets/ipad-mini-2021-starlight/thumbnail.webp"
    ],
    "rating": 3.2,
    "reviewCount": 87,
    "inStock": true,
    "sku": "GK-TA-0159",
    "shortFeatures": [
      "The iPad Mini 2021 in Starlight is a compact and powerful tablet from Apple",
      "Featuring a stunning Retina display, powerful A-series chip, and a sleek design, it offers a premium tablet experience"
    ],
    "description": [
      "The iPad Mini 2021 in Starlight is a compact and powerful tablet from Apple. Featuring a stunning Retina display, powerful A-series chip, and a sleek design, it offers a premium tablet experience."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Apple"
      },
      {
        "key": "Weight",
        "value": "5g"
      },
      {
        "key": "Dimensions",
        "value": "17.03 × 5.34 × 29.62 mm"
      },
      {
        "key": "Warranty",
        "value": "2 year warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 1-2 business days"
      }
    ],
    "inTheBox": [
      "Laptop",
      "USB-C Power Adapter",
      "Quick Start Guide"
    ],
    "isHotDeal": false,
    "isNewArrival": false
  },
  {
    "id": "160",
    "name": "Samsung Galaxy Tab S8 Plus Grey",
    "brand": "Samsung",
    "category": "Laptops",
    "price": 599.99,
    "originalPrice": 692.11,
    "image": "https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-s8-plus-grey/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-s8-plus-grey/1.webp",
      "https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-s8-plus-grey/2.webp",
      "https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-s8-plus-grey/3.webp",
      "https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-s8-plus-grey/4.webp",
      "https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-s8-plus-grey/thumbnail.webp"
    ],
    "rating": 4.7,
    "reviewCount": 174,
    "inStock": true,
    "sku": "GK-TA-0160",
    "shortFeatures": [
      "The Samsung Galaxy Tab S8 Plus in Grey is a high-performance Android tablet by Samsung",
      "With a large AMOLED display, powerful processor, and S Pen support, it's ideal for productivity and entertainment"
    ],
    "description": [
      "The Samsung Galaxy Tab S8 Plus in Grey is a high-performance Android tablet by Samsung. With a large AMOLED display, powerful processor, and S Pen support, it's ideal for productivity and entertainment."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Samsung"
      },
      {
        "key": "Weight",
        "value": "1g"
      },
      {
        "key": "Dimensions",
        "value": "6.11 × 25.85 × 26.85 mm"
      },
      {
        "key": "Warranty",
        "value": "3 months warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships in 2 weeks"
      }
    ],
    "inTheBox": [
      "Laptop",
      "USB-C Power Adapter",
      "Quick Start Guide"
    ],
    "isHotDeal": true,
    "isNewArrival": false
  },
  {
    "id": "161",
    "name": "Samsung Galaxy Tab White",
    "brand": "Samsung",
    "category": "Laptops",
    "price": 349.99,
    "originalPrice": 427.86,
    "image": "https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/thumbnail.webp",
    "images": [
      "https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/1.webp",
      "https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/2.webp",
      "https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/3.webp",
      "https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/4.webp",
      "https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/thumbnail.webp"
    ],
    "rating": 3.7,
    "reviewCount": 108,
    "inStock": true,
    "sku": "GK-TA-0161",
    "shortFeatures": [
      "The Samsung Galaxy Tab in White is a sleek and versatile Android tablet"
    ],
    "description": [
      "The Samsung Galaxy Tab in White is a sleek and versatile Android tablet. With a vibrant display, long-lasting battery, and a range of features, it offers a great user experience for various tasks."
    ],
    "specifications": [
      {
        "key": "Brand",
        "value": "Samsung"
      },
      {
        "key": "Weight",
        "value": "5g"
      },
      {
        "key": "Dimensions",
        "value": "15.05 × 5.37 × 11.82 mm"
      },
      {
        "key": "Warranty",
        "value": "3 months warranty"
      },
      {
        "key": "Shipping",
        "value": "Ships overnight"
      }
    ],
    "inTheBox": [
      "Laptop",
      "USB-C Power Adapter",
      "Quick Start Guide"
    ],
    "isHotDeal": true,
    "isNewArrival": false
  }
];
